In [1]:
pip install csv

ERROR: Could not find a version that satisfies the requirement csv
ERROR: No matching distribution found for csv
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install pandas

Requirement already satisfied: pandas in /usr/lib/python3/dist-packages (1.1.5)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

In [10]:
file=pd.read_csv('/home/k/Documents/a.csv')
file

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,2,21-05-19 8:29,21-05-19 9:29,34.808868,-82.269157,34.808868,-82.269157,0.000,Accident on Tanner Rd at Pennbrooke Ln.,439.0,...,False,False,False,False,False,False,Day,Day,Day,Day
1,2,07-10-19 17:43,07-10-19 19:42,35.090080,-80.745560,35.090080,-80.745560,0.000,Accident on Houston Branch Rd at Providence Br...,3299.0,...,False,False,False,False,False,False,Day,Day,Day,Day
2,2,13-12-20 21:53,13-12-20 22:44,37.145730,-121.985052,37.165850,-121.988062,1.400,Stationary traffic on CA-17 from Summit Rd (CA...,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3,2,17-04-18 16:51,17-04-18 17:50,39.110390,-119.773781,39.110390,-119.773781,0.000,Accident on US-395 Southbound at Topsy Ln.,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
4,3,31-08-16 17:40,31-08-16 18:10,26.102942,-80.265091,26.102942,-80.265091,0.000,Accident on I-595 Westbound at Exit 4 / Pine I...,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,2,13-12-20 19:20,13-12-20 22:02,38.013478,-122.259260,38.015578,-122.270930,0.652,WB 4 TO WB 80 CON. MC - PULLED TO RHS - RIDER ...,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
4997,3,01-08-18 7:10,01-08-18 7:39,36.225597,-86.776039,36.225597,-86.776039,0.000,Accident on I-24 Eastbound at I-65.,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
4998,2,27-03-20 17:39,27-03-20 18:39,32.338220,-86.179150,32.338220,-86.179150,0.000,At CR-626/Vaughn Rd - Accident.,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
4999,2,26-03-18 15:56,26-03-18 16:25,29.736551,-95.290504,29.736551,-95.290504,0.000,Accident on Canal St at 75th St.,7501.0,...,False,False,False,False,True,False,Day,Day,Day,Day
5000,2,07-06-19 15:00,07-06-19 15:58,33.928638,-118.280182,NaN,NaN,0.360,Accident on exit ramp from I-110 Northbound at...,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day

In [12]:
file2=pd.read_csv('/home/k/Documents/1.csv')
file2

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,3,21-06-18 7:50,21-06-18 13:50,32.92393,-96.77563,32.92379,-96.76877,0.398,Ramp to US-75 - Accident. Two lanes blocked. H...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
1,2,22-12-17 17:23,22-12-17 17:53,33.236919,-87.560966,33.236919,-87.560966,0,Accident on US-82 McFarland Blvd Westbound at ...,3200,...,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,Night,Night,Day,Day
2,2,11-12-19 15:27,11-12-19 16:38,33.02304,-117.07853,33.02304,-117.07853,0,At Rancho Bernardo Rd - Accident. Obstruction ...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
3,2,09-10-19 15:06,09-10-19 15:39,38.366671,-122.712364,38.366671,-122.712364,0,At Commerce Blvd/Wilfred Ave - Accident.,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
4,2,03-12-19 23:44,04-12-19 1:56,38.597976,-121.383093,38.597976,-121.383093,0,At Arden Way - Accident.,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Night,Night,Night,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2525,2,31-01-20 8:42,31-01-20 9:42,36.30072,-86.711159,36.30072,-86.711159,0,Accident on I-65 Northbound near Alta Loma Rd.,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
2526,3,17-12-16 20:34,17-12-16 21:02,42.308929,-83.174988,NaN,NaN,0.01,Left lane blocked due to accident on I-94 East...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Night,Night,Night,Night
2527,2,25-03-20 5:24,25-03-20 6:39,45.593578,-122.730339,45.593578,-122.730339,0,Accident on Columbia Way near Macrum Ave. No r...,9771,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Night,Night,Night,Day
2528,3,05-06-20 16:57,05-06-20 17:57,36.04259,-86.6063,36.04222,-86.60599,0.031,At Old Hickory Blvd - Accident. Roadwork. Lane...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
2529,2,12-04-16 19:51,12-04-16 20:41,33.070168,-116.884804,NaN,NaN,0.01,Accident on CA-78 Haverford Rd Westbound at We...,1499,...,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,Night,Night,Day,Day

In [56]:
m = pd.merge(file, file2, on='Start_Time')

m.head()

,Severity_x,Start_Time,End_Time_x,Start_Lat_x,Start_Lng_x,End_Lat_x,End_Lng_x,Distance(mi)_x,Description_x,Number_x,...,Roundabout_y,Station_y,Stop_y,Traffic_Calming_y,Traffic_Signal_y,Turning_Loop_y,Sunrise_Sunset_y,Civil_Twilight_y,Nautical_Twilight_y,Astronomical_Twilight_y
0,2,05:00.0,30:00.0,42.385137,-83.280821,42.385475,-83.259075,1.110,Slow traffic on I-96 E - Edward J Jeffries Fwy...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
1,2,05:00.0,45:00.0,33.172198,-87.521263,33.174898,-87.480293,2.377,Incident on I-20 EB near MM 75 Left shoulder c...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
2,2,25-11-19 12:45,25-11-19 13:15,40.285888,-76.821141,40.285888,-76.821141,0.000,At Union Deposit Rd/Exit 48 - Accident. Lane b...,NaN,...,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,Day,Day,Day,Day
3,2,20:00.0,59:30.0,33.992068,-118.402353,34.003089,-118.411069,0.911,Slow traffic on I-405 from Sepulveda Blvd (I-4...,NaN,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day
4,2,04-12-18 7:53,04-12-18 9:54,28.450769,-82.557404,28.450769,-82.557404,0.000,Lane blocked due to accident on Horizon Dr at ...,10096.0,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Day,Day,Day,Day

In [25]:

import pandas as pd
import numpy as np

import missingno as msno

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
ACCEDENTS_PATH = "/home/k/Documents/a.csv"
acc_df = pd.read_csv(ACCEDENTS_PATH, 
                     parse_dates=["Start_Time"], 
                     dtype={"Accident_Index": object})

In [28]:


data = acc_df.copy()

In [29]:
data.head()

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,2,21-05-19 8:29,21-05-19 9:29,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,439.0,...,False,False,False,False,False,False,Day,Day,Day,Day
1,2,07-10-19 17:43,07-10-19 19:42,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,3299.0,...,False,False,False,False,False,False,Day,Day,Day,Day
2,2,13-12-20 21:53,13-12-20 22:44,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3,2,17-04-18 16:51,17-04-18 17:50,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
4,3,31-08-16 17:40,31-08-16 18:10,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [31]:
data["Start_Time"].value_counts()/data.shape[0]

48:00.0           0.0006
02-12-20 13:35    0.0004
25-10-16 7:21     0.0004
14-12-20 16:20    0.0004
24-11-20 14:09    0.0004
                   ...
07-02-18 5:56     0.0002
09-10-19 11:37    0.0002
09-08-17 15:07    0.0002
02-11-20 6:50     0.0002
26-03-19 17:37    0.0002
Name: Start_Time, Length: 4984, dtype: float64

In [41]:



import researchpy as rp
table, results = rp.crosstab(data['Severity'], 
                             data["Start_Time"],
                            
                             prop= 'col', test= 'chi-square')
    
table

           Start_Time                                               \
Start_Time    00:00.0 00:40.0 00:54.0 01-01-20 19:21 01-01-20 2:43
Severity
1                 0.0     0.0     0.0            0.0           0.0
2               100.0   100.0   100.0          100.0         100.0
3                 0.0     0.0     0.0            0.0           0.0
4                 0.0     0.0     0.0            0.0           0.0
All             100.0   100.0   100.0          100.0         100.0

                                                                      \
Start_Time 01-01-20 5:52 01-01-20 6:22 01-02-17 12:09 01-02-17 16:17
Severity
1                    0.0           0.0            0.0            0.0
2                  100.0         100.0          100.0          100.0
3                    0.0           0.0            0.0            0.0
4                    0.0           0.0            0.0            0.0
All                100.0         100.0          100.0          100.0

                           ...                                          \
Start_Time 01-02-17 16:48  ... 52:31.0 54:00.0 54:30.0 55:00.0 56:00.0
Severity                   ...
1                     0.0  ...     0.0     0.0     0.0     0.0     0.0
2                   100.0  ...   100.0   100.0   100.0   100.0   100.0
3                     0.0  ...     0.0     0.0     0.0     0.0     0.0
4                     0.0  ...     0.0     0.0     0.0     0.0     0.0
All                 100.0  ...   100.0   100.0   100.0   100.0   100.0


Start_Time 57:23.0 58:30.0 58:34.0 59:00.0     All
Severity
1              0.0     0.0     0.0     0.0    1.18
2            100.0   100.0   100.0   100.0   73.05
3              0.0     0.0     0.0     0.0   22.20
4              0.0     0.0     0.0     0.0    3.58
All          100.0   100.0   100.0   100.0  100.00

[5 rows x 4985 columns]

In [42]:
import researchpy as rp
table, results = rp.crosstab(data['Severity'], 
                             data["Description"],
                            
                             prop= 'col', test= 'chi-square')
    
table

                                                                    Description  \
Description #'2 lane blocked due to accident on Florin Rd Westbound at 65th St.
Severity
1                                                          0.0
2                                                        100.0
3                                                          0.0
4                                                          0.0
All                                                      100.0

                                                                                   \
Description #1 #2 #3 lane blocked due to accident on I-35 Southbound at Evans Rd.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                  \
Description #1 #2 lane blocked due to accident on I-10 Eastbound at Central Ave.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                    \
Description #1 #2 lane blocked due to accident on I-35W Southbound at Risinger Rd.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                                    \
Description #1 #2 lane blocked due to accident on I-635 Eastbound at Exit 15 Lyndon B Johnson Fwy.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                                                 \
Description #1 #2 lane blocked due to accident on I-80 Westbound after Exit 11 University Ave. SigAlert issued.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                                    \
Description #1 #2 lane blocked due to accident on I-880 Southbound near Exits 33A 33B Marina Blvd.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                             \
Description #1 & #2 lane blocked due to accident on I-5 Southbound at Exit 628 Liberal Ave.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                            \
Description #1 &amp; #2 lane blocked due to accident on I-35W Southbound at Basswood Blvd.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

                                                                                          \
Description #1 and #2 lane blocked due to accident on I-10 Westbound after Santa Fe Ave.
Severity
1                                                          0.0
2                                                          0.0
3                                                        100.0
4                                                          0.0
All                                                      100.0

             ...                                                               \
Description  ... WB 10 AT GRAND. CIV MC DOWN IN LNS ; UNK IF OTHER VEHS INVLD
Severity     ...
1            ...                                                0.0
2            ...                                              100.0
3            ...                                                0.0
4            ...                                                0.0
All          ...                                              100.0

                                                                                \
Description WB 4 TO WB 80 CON. MC - PULLED TO RHS - RIDER LAYING ON THE GROUND
Severity
1                                                          0.0
2                                                        100.0
3                                                          0.0
4                                                          0.0
All                                                      100.0

                                                                               \
Description WB JEO. [Rotation Request Comment] 1039 W A P Tow 44 530-295-9316
Severity
1                                                          0.0
2                                                        100.0
3                                                          0.0
4                                                          0.0
All                                                      100.0

                                      \
Description WB JWO. 1039 PLACER FIRE
Severity
1                                0.0
2                              100.0
3                                0.0
4                                0.0
All                            100.0

                                                                                \
Description WB JWO. PER FORESTHILL TOW ETA 20 MINS FRM ROSEVILLE / 45-283 CPYS
Severity
1                                                          0.0
2                                                        100.0
3                                                          0.0
4                                                          0.0
All                                                      100.0

                                                              \
Description WHITNEY and E COUNTRY CLUB. CORR LINE 39 1039 BT
Severity
1                                                        0.0
2                                                      100.0
3                                                        0.0
4                                                        0.0
All                                                    100.0

                                                      \
Description [Appended 08:35:23] UNK ETA NO CLR UNITS
Severity
1                                                0.0
2                                              100.0
3                                                0.0
4                                                0.0
All                                            100.0

                                                                                          \
Description [Rotation Request Comment] 1039 AUTO AIDE FOR EVIDENCE 951-735-2180 / CPS FB
Severity
1                                                          0.0
2                                                        100.0
3                                                          0.0
4                                                          0.0
All                                                      100.0

                                                                              \
Description [Rotation Request Comment] 1039 S AND R TOW XXX 760-722-6686 XXX
Severity
1                                                          0.0
2                                                        100.0
3                                                          0.0
4                                                          0.0
All                                                      100.0


Description     All
Severity
1              1.18
2             73.05
3             22.20
4              3.58
All          100.00

[5 rows x 4874 columns]